name: Generate Certificate

on: [push]

jobs:
  generate_certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: PowerShell/setup-powershell@v1
      
    - name: Generate Certificate
      shell: pwsh
      run: |
        $date_now = Get-Date
        $extended_date = $date_now.AddYears(3)
        $cert = New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname RetroPass -notafter $extended_date

    - name: Export Certificate
      shell: pwsh
      run: |
        $cert | Export-Certificate -FilePath ./certificate.crt
        $cert | Export-PfxCertificate -FilePath ./certificate.pfx -Password (ConvertTo-SecureString -String "RetroPass" -AsPlainText -Force)

    - name: Upload Certificate
      uses: actions/upload-artifact@v2
      with:
        name: certificate
        path: |
          ./certificate.crt
          ./certificate.pfx
