name: RetroPass Build 

on:
 workflow_dispatch:

jobs:
  generate-pfx:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Create PFX file
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com" RetroPass.sln /CreatePfx "RetroPassKey.pfx" /Password "${{ secrets.PFX_PASSWORD }}"

    - name: Save PFX as artifact
      uses: actions/upload-artifact@v2
      with:
        name: generated-pfx
        path: RetroPassKey.pfx
